# Generated by Django 3.2.5 on 2021-11-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldKnow', models.CharField(default='fieldKnow', max_length=40)),
                ('question', models.CharField(default='question', max_length=250)),
                ('answer', models.CharField(default='ans', max_length=250)),
            ],
        ),
    ]
