# Generated by Django 3.2.5 on 2021-12-02 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fields',
        ),
        migrations.CreateModel(
            name='User_Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.ForeignKey(db_column='fieldKnow', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.qa')),
                ('username', models.ForeignKey(db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
