# Generated by Django 3.2.5 on 2021-12-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211202_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManyQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_all', models.IntegerField(default=3)),
                ('questions_right', models.IntegerField(default=2)),
            ],
        ),
    ]
