# Generated by Django 3.2.5 on 2021-12-04 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_manyquestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_field',
            name='field',
            field=models.ForeignKey(blank=True, db_column='fieldKnow', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.qa'),
        ),
    ]
