# Generated by Django 3.2.5 on 2021-12-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_field_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='manyquestions',
            name='name',
            field=models.CharField(default='pass1', max_length=250),
        ),
    ]
