# Generated by Django 3.2.5 on 2022-05-14 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_manyquestions_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('content', models.CharField(default='content', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id_k', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('content', models.CharField(default='content', max_length=50)),
                ('interest', models.ForeignKey(blank=True, db_column='id', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.interests')),
            ],
        ),
        migrations.CreateModel(
            name='User_interest',
            fields=[
                ('id_ui', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('interest', models.ForeignKey(blank=True, db_column='id', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.interests')),
                ('username', models.ForeignKey(db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='qa',
            name='fieldKnow',
        ),
        migrations.RemoveField(
            model_name='qa',
            name='id',
        ),
        migrations.RemoveField(
            model_name='qa',
            name='question',
        ),
        migrations.AddField(
            model_name='qa',
            name='content',
            field=models.CharField(default='question', max_length=500),
        ),
        migrations.AddField(
            model_name='qa',
            name='id_qa',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qa',
            name='answer',
            field=models.CharField(default='ans', max_length=50),
        ),
        migrations.DeleteModel(
            name='User_Field',
        ),
        migrations.AddField(
            model_name='qa',
            name='interest',
            field=models.ForeignKey(blank=True, db_column='id', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.interests'),
        ),
    ]
