# Generated by Django 3.2.5 on 2022-06-06 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220514_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keywords',
            old_name='content',
            new_name='contentkey',
        ),
        migrations.RenameField(
            model_name='qa',
            old_name='content',
            new_name='contentqa',
        ),
        migrations.AlterField(
            model_name='keywords',
            name='interest',
            field=models.ForeignKey(blank=True, db_column='content', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.interests'),
        ),
        migrations.AlterField(
            model_name='qa',
            name='interest',
            field=models.ForeignKey(blank=True, db_column='content', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.interests'),
        ),
    ]
